apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: kwetter
  labels:
    app: neo4j
spec:
  ports:
  - protocol: TCP
    port: 7474
    targetPort: 7474
    name: http
  - protocol: TCP
    port: 7473
    targetPort: 7473
    name: https
  - protocol: TCP
    port: 7687
    targetPort: 7687
    name: bolt
  selector:
    app: neo4j
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: kwetter
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: neo4j
      version: 4.2.6
  template:
    metadata:
      labels:
        app: neo4j
        version: 4.2.6
    spec:
      containers:
      - name: neo4j
        image: neo4j:4.2.6
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: neo4j-secret
        ports:
          - containerPort: 7474
            name: http
          - containerPort: 7687
            name: bolt
          - containerPort: 7473
            name: https
        resources:
          limits:
            memory: 600Mi
            cpu: 400m
        volumeMounts:
        - name: neo4j-data-volume
          mountPath: /var/lib/neo4j/data
      volumes:
      - name: neo4j-data-volume
        persistentVolumeClaim:
          claimName: neo4j-data-volume-claim