apiVersion: v1
kind: PersistentVolume
metadata:
  name: kwetter-db-volume
  namespace: kwetter
  labels:
    type: local
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 24Gi
  hostPath:
    path: "/mnt/data"