name: "Builds and publish a docker image"
description: "Builds and publishes the docker image"
inputs:
  image: 
    description: "The docker image."
    required: true
  tag: 
    description: "The version tag."
    required: true
runs:
  using: "composite"
  steps:
    # Builds and publishes the image
    - name: Build and push Docker image 
      shell: bash
      run: |
        echo "Building docker image"
        docker build -t ${{ secrets.NEURALM_REGISTRY }}/${{ inputs.image }}:${{ inputs.tag }} -f ./${{ inputs.image }}.Dockerfile .
        echo "Publishing docker image"
        docker push ${{ secrets.NEURALM_REGISTRY }}/${{ inputs.image }}:${{ inputs.tag }}
    