apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-volume-claim
  namespace: kwetter
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-volume
  namespace: kwetter
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/redis/
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-data-volume-claim
    namespace: kwetter
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - minikube