apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kwetter-kweet-db-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-storage