apiVersion: v1
kind: Service
metadata:
  name: kwetter-follow-db
  namespace: kwetter
  labels:
    app: kwetter-follow-db
    service: kwetter-follow-db
spec:
  selector:
    app: kwetter-follow-db-pod
  ports:
  - protocol: TCP
    name: tcp-mssql
    port: 1433
    targetPort: 1433
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwetter-follow-db
  namespace: kwetter
spec:
  selector:
    matchLabels:
      app: kwetter-follow-db-pod
      version: latest
  template:
    metadata:
      labels:
        app: kwetter-follow-db-pod
        version: latest
    spec:
      containers:
      - name: kwetter-follow-db-container
        image: mcr.microsoft.com/mssql/server:2019-latest
        resources:
          limits:
            memory: 3Gi
            cpu: 1000m
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"
        volumeMounts:
        - name: kwetter-follow-db-volume
          mountPath: /var/opt/mssql
      volumes:
      - name: kwetter-follow-db-volume
        persistentVolumeClaim:
          claimName: kwetter-follow-db-volume-claim
