apiVersion: v1
kind: PersistentVolume
metadata:
  name: kwetter-user-db-volume
  namespace: kwetter
  labels:
    type: local
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 4Gi
  hostPath:
    path: "/mnt/data/kwetter-user-db"