apiVersion: v1
kind: Service
metadata:
  name: kwetter-user-db
  namespace: kwetter
  labels:
    app: kwetter-user-db
    service: kwetter-user-db
spec:
  selector:
    app: kwetter-user-db-pod
  ports:
  - protocol: TCP
    name: tcp-psql
    port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwetter-user-db
  namespace: kwetter
spec:
  selector:
    matchLabels:
      app: kwetter-user-db-pod
      version: latest
  template:
    metadata:
      labels:
        app: kwetter-user-db-pod
        version: latest
    spec:
      containers:
      - name: kwetter-user-db-container
        image: postgres:13.3
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: 800Mi
            cpu: 300m
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: kwetter-user-db-secret
        volumeMounts:
        - name: kwetter-user-db-volume
          mountPath: /var/lib/postgresql/data
        - name: config
          mountPath: /var/lib/postgresql/postgresql.conf
          subPath: postgresql.conf
          readOnly: true
        args:
          - "-c"
          - "config_file=/var/lib/postgresql/postgresql.conf"
      volumes:
      - name: kwetter-user-db-volume
        persistentVolumeClaim:
          claimName: kwetter-user-db-volume-claim
      - name: config
        configMap:
          name: kwetter-postgres-configmap