name: Load Tests

on:
  workflow_dispatch:

jobs:
  test:
    environment:
      name: staging
    name: Authorization Load Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Verify Username Uniqueness Load Test ConfigMap
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        KUBECTL_VERSION: "1.20"
      with:
        args: '"create configmap -n kwetter-testing verify-username-uniqueness-load-test-configmap --from-file src/Testing/Kwetter.LoadTests/test.js"'

    - name: Run Verify Username Uniqueness Load Test
      uses: steebchen/kubectl@master
      if: ${{ success() }}
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        KUBECTL_VERSION: "1.20"
      with:
        args: '"apply -n kwetter-testing -f ./K8s/k6/verify-username-uniqueness-load-test.yaml"'

    - name: Await Verify Username Uniqueness Load Test Completion
      uses: steebchen/kubectl@master
      if: ${{ success() }}
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        KUBECTL_VERSION: "1.20"
      with:
        args: '"wait -n kwetter-testing --timeout=600s --for=condition=complete job -l k6_cr=verify-username-uniqueness-load-test,job-name!=verify-username-uniqueness-load-test-starter"'
    
    - name: Get Logs From Verify Username Uniqueness Load Test
      uses: steebchen/kubectl@master
      if: ${{ success() }}
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        KUBECTL_VERSION: "1.20"
      with:
        args: '"logs -n kwetter-testing --tail 23 -l k6_cr=verify-username-uniqueness-load-test,job-name!=verify-username-uniqueness-load-test-starter"'

    - name: Delete Verify Username Uniqueness Load Test Pods
      uses: steebchen/kubectl@master
      if: ${{ always() }}
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        KUBECTL_VERSION: "1.20"
      with:
        args: '"delete -n kwetter-testing -f ./K8s/k6/verify-username-uniqueness-load-test.yaml"'

    - name: Delete Verify Username Uniqueness Load Test ConfigMap
      uses: steebchen/kubectl@master
      if: ${{ always() }}
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        KUBECTL_VERSION: "1.20"
      with:
        args: '"delete cm -n kwetter-testing verify-username-uniqueness-load-test-configmap"'